### ISSUE TITLE
Nginx throwing bad gateway - may you help me?

### ISSUE THREAD

**Issue by lucasctd** [ilanco/vscode-devcontainer-php7#1]
Hi buddy,

thx for sharing your files.
I am trying to build my own but it seems nginx can't reach php-fpm, I don't know why.

**docker-compose**
```yaml
version: '3.8'
services:
    server:
        image: nginx:1.19-alpine
        restart: on-failure
        volumes:
            - ../:/var/www/html
            - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
        network_mode: service:app

    app:
        restart: on-failure
        build:
            context: php
        volumes:
            - ../:/var/www/html
        environment:
            PHP_IDE_CONFIG: "serverName=localhost"
        network_mode: service:db

    db:
        image: mariadb:latest
        restart: on-failure
        environment:
            MARIADB_ROOT_PASSWORD: password
            MARIADB_DATABASE: letter_jacket_designer_builder_api
```

**site.conf**

```
server {
    listen 80;
    root /var/www/html/public;
    client_max_body_size 1024M;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";

    index index.html index.htm index.php;

    charset utf-8;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    error_page 404 /index.php;

    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
```

for some reason every time I try to load my app I am getting a 502 error. I know most of the time it happens is because nginx is not able to reach php-fpm, but I have no idea how I would be able to get the logs from nginx container.

My codespace is built on top of the php-fpm container so I can have access to its files, logs etc, but for nginx and my mariadb instance I dunno where github store their files.

do you know how I can access the other containers? Or do you know why nginx is not able to reach php-fpm?
I would usually do `docker exec -it` if they were running on my local machine.

Thanks in advance.
